#!/bin/bash

: <<'FUNCTION'
Description: Function check if the table has cache and creates if not
Parameters:
  $1 - Table id to check for the cache
FUNCTION
cache_has_cache() {
	local tmp="CACHE_${1}"
}

# Do cache for a specify object
# $1 - The kind of object
cache_do_cache() {
	if cache_has_cache $1; then
		return 0
	fi
	
	return 0
}
