#!/bin/bash

table_execute() {
	local OUT=""
	local value="${TOKENS[TABLE]}"
	
	LOGGER_MSG="Table: $value"
	eval $LOGGER DEBUG

	# Find the table id
	find_table_by_name OUT "$value"
	RES=$?
	if [ ! $RES == 0 ]; then
		LOGGER_MSG="Table '${TOKENS[TABLE]}' not exists"
		eval $LOGGER ERROR
		return 1
	fi

	# Just call the printer_dump_table
	printer_dump_table "" $OUT
}
