#!/bin/bash

show_execute() {
	LOGGER_MSG="Config to show: ${TOKENS[VALUE]}"
	eval $LOGGER DEBUG

	local option="${TOKENS[VALUE]^^}"

	if [ "$option" == "RESERVED" ]; then
		declare -A TAB_PRINTER

		TAB_PRINTER[header]="| value${MGC_FLD}|"
		TAB_PRINTER[fields]=1

		local k
		for k in `seq 0 ${#RESERVED[@]}`; do
			TAB_PRINTER[$((k+1))]="| ${RESERVED[$k]} ${MGC_FLD}|"
		done
		TAB_PRINTER[rows]=$k

		printer TAB_PRINTER
		return 0
	fi

	# check if value exists
	if [[ ! "$option" == "ALL" && -z ${GC[$option]} ]]; then
		LOGGER_MSG="Value $option is not a option"
		eval $LOGGER ERROR
		return 1
	fi

	declare -A TAB_PRINTER

	TAB_PRINTER[header]="| option${MGC_FLD}| value${MGC_FLD}|"
	TAB_PRINTER[fields]=2
	TAB_PRINTER[rows]=1

	if [ "$option" == "ALL" ]; then
		local k=1
		for i in "${!GC[@]}"; do
			let k++
			TAB_PRINTER[$k]="| $i ${MGC_FLD}| ${GC[$i]} ${MGC_FLD}|"
		done
		TAB_PRINTER[rows]=$k
	else
		local value="${GC[$option]}"

		TAB_PRINTER[1]="| $option ${MGC_FLD}| $value ${MGC_FLD}|"
	fi

	printer TAB_PRINTER
	return 0
}
