#!/bin/bash

table_execute() {
	local OUT=""
	local value="${TOKENS[TABLE]}"
	
	LOGGER_MSG="Table: $value"
	eval $LOGGER DEBUG

	# Find the table struct
	declare -A TS
	TS[table]="$value"
	if ! table_get_struct_by_name TS; then
		LOGGER_MSG="Table '${TS[table]}' not found"
		eval $LOGGER ERROR
		return 1
	fi

	# Just call the printer_dump_table
	printer_dump_table "" ${TS[id]}
}
