#!/bin/bash

set_execute() {
	LOGGER_MSG="Total configuration: ${TOKENS[KV_total]}"
	eval $LOGGER DEBUG

	local sz=${TOKENS[KV_total]}
	local i=0
	for i in `${PRG_SEQ} 1 $sz`; do
		local set_key="${TOKENS[KV_KEY_$i]^^}"
		local set_value="${TOKENS[KV_VALUE_$i]}"

		LOGGER_MSG="Key: $set_key => Value: $set_value"
		eval $LOGGER DEBUG1

		# Check if exists
		# Check the available values in var
		# Need a new value? Add a new array in the GC variable in var file
		if [ ! -z ${GC[$set_key]} ]; then
			if [ -z ${GC_ORIGINAL[$set_key]} ]; then
				GC_ORIGINAL[$set_key]="${GC[$set_key]}"
			fi

			GC[$set_key]="$set_value"
		else		
			LOGGER_MSG="Command ${set_key} not found"
			eval $LOGGER ERROR
		fi
	done

	report_finish
}
