#!/bin/bash

. log
. functions
. parser
. parserv2
. cmd_table
. cmd_create
. cmd_set

execute() {
	# Clear this "object" (I know, variable, OK)
	unset SQLOBJ
	declare -A SQLOBJ

	# [ parser ]
	# Aqui preenchemos o objeto SQLOBJ
	#parser "${INPUT_CMD}"
	parse_sql "${INPUT_CMD}" > /dev/null
	RET="$?"

	if [ ! "$RET" == "0" ]; then
		LOGGER_MSG="There is a error in the SQL: ${ERROR[msg]}"
		eval $LOGGER ERROR

		return $RET
	fi

	# Buscar código dos objetos
	#post_parser

	CMD="${TOKENS[CMD]}"

	LOGGER_MSG="Command |$CMD|"
	eval $LOGGER DEBUG1

	case "${CMD}" in
		SET)
			# [ cmd_set ]
			set_execute
			;;
		TABLE)
			# [ cmd_table ]
			table_execute
			;;
		CREATE)
			case "${TOKENS[OBJECT]}" in
				SCHEMA)	create_schema_execute ;;
			esac
			;;
		*)
			LOGGER_MSG="Unknown command: ${CMD}"
			eval $LOGGER ERROR
			;;
	esac
}
