#!/bin/bash

. log
. functions
. parser
. parserv2
. cmd_table
. cmd_create
. cmd_set
. cmd_show
. cmd_reset
. cmd_truncate

execute() {
	# Clear this "object" (I know, variable, OK)
	unset SQLOBJ
	declare -A SQLOBJ

	# [ parser ]
	# Aqui preenchemos o objeto SQLOBJ
	#parser "${INPUT_CMD}"
	parse_sql "${INPUT_CMD}" > /dev/null
	RET="$?"

	if [ ! "$RET" == "0" ]; then
		LOGGER_MSG="There is a error in the SQL: ${ERROR[msg]}"
		eval $LOGGER ERROR

		return $RET
	fi

	# Buscar código dos objetos
	#post_parser

	CMD="${TOKENS[CMD]}"

	LOGGER_MSG="Command |$CMD|"
	eval $LOGGER DEBUG1

	# The name of the function is standardized
	local fnc_call="${CMD,,}_execute"

	fn_exist $fnc_call
	RES=$?

	if [ ! "$RES" == "0" ]; then
		LOGGER_MSG="Unknown command: ${CMD}"
		eval $LOGGER ERROR
		return 1
	fi

	eval $fnc_call	
}
