#!/bin/bash

# $1 - Variable Name Associative Array
attrs_search() {
	# FA = FindAttrs
	declare -n FA=$1

	# FA[total]=total attrs
	# FA[#_name]=name of the attr
	# FA[#_type]=type of the attr

	declare -A DATA
	# We are reading the table attrs
	DATA[file]=$CTABLE_ATTRS
	init_file DATA

	local i=0
	# Loop in all records of the table attrs
	while next_record DATA REC; do
		local val=""
		local IT=""

		# 1 - id
		# 2 - table_id
		# 3 - attr name
		# 4 - types
		# 5 - size
		# 6 - default
		# 7 - null
		hex_to_int val ${REC[2]}

		if [ "${FA[id]}" == "$val" ]; then
			let i++

			# Type attr is int, so transform it
			hex_to_int IT "${REC[4]}"

			FA[${i}_name]="${REC[3]}"
			FA[${i}_type]="${IT}"
			FA[${i}_default]="${REC[6]}"
			FA[${i}_null]="${REC[7]}"
		fi
	done
	FA[total]=$i

	# $i contains the count of attrs found, so if 0 menas that
	#  didnt found any attr for this table
	if [ $i -eq 0 ]; then
		return 1
	else
		return 0
	fi
}

# $1 - Array variable
attrs_get_header() {
	declare -n FA=$1
	local i=0
	local val="|"
	for i in `$PRG_SEQ 1 ${FA[total]}`; do
		val="$val ${FA[${i}_name]} ${MGC_FLD}|"
	done
	FA[header]="$val"
}
