#!/bin/bash

: <<'FUNCTION'
Desciption: Find the table ID by the name
Parameters:
 $1 - OUT ID
 $2 - Table name
FUNCTION
find_table_by_name() {
	local _RET=$1
	local RETCODE=1

	declare -A DATA
	DATA[file]=$CTABLE_TABLES
	init_file DATA

	while next_record DATA REC; do
		LOGGER_MSG="table: ${REC[2]}"
		eval $LOGGER DEBUG2

		# The name of the table is in the index 2
		# The id of the table is in the index 1
		if [ "${REC[2]}" == "$2" ]; then
			eval $LOGGER DEBUG "Found table with id: ${REC[1]}"
			RETCODE=0
			break
		fi
	done

	# IV = Int Value
	hex_to_int IV "${REC[1]}"

	eval $_RET="$IV"
	return $RETCODE
}
