#!/bin/bash

# $1 - Object
# $2 - Fields
# $3 - Header
printer_init() {
	declare -n LPD=$1
	LPD[rows]=0
	LPD[header]="$3"
	LPD[fields]=$2
}

printer_add() {
	# Local Printer Data
	declare -n LPD=$1

	# We inc before
	let LPD[rows]++

	LPD[${LPD[rows]}]="$2"

}

printer() {
	declare -n PRINT=$1

	local nOC=${PRINT[fields]}
	local table=""
	local delimiter=""
	local line=""

	delimiter="$(${PRG_PRINTF} "%s${MGC_FLD}+" "$(repeatString "${MGC_FLD}+" $nOC)")"
	table="${delimiter}\n${PRINT[header]}\n${delimiter}\n"

	for i in `${PRG_SEQ} 1 ${PRINT[rows]}`; do
		line="${PRINT[$i]}"

		table="${table}${line}\n"
	done

	${PRG_ECHO} -e "${table}\n${delimiter}" | ${PRG_COLUMN} -t -s"${MGC_FLD}" | ${PRG_AWK} '/^\+/{gsub(" ", "-", $0)}1'
	${PRG_ECHO} " (${PRINT[rows]} rows fetched)"
}

# $1 - Title
# $2 - Tablea ID
# $3 - Header
printer_dump_table() {
	local _TITLE=$1
	local _TABLE=$2
	local _HEADER=$3

	local HEADER="|${_HEADER//,/${MGC_FLD}|}${MGC_FLD}|"

	# Lets find the attrs of this relation
	declare -A TAB_ATTR
	TAB_ATTR[id]=$2
	find_attrs TAB_ATTR
	declare -p TAB_ATTR

	declare -A TAB_PRINT
	printer_init TAB_PRINT 3 "$HEADER"

	declare -A DATA
	DATA[file]=$_TABLE
	init_file DATA

	while next_record DATA REC; do
		local ROW=""
		ROW="|${REC[1]}${MGC_FLD}|${REC[2]} ${MGC_FLD}|${REC[3]} ${MGC_FLD}|"

		printer_add TAB_PRINT "$ROW"
	done

	if [ ! "$1" == "" ]; then
		${PRG_ECHO} "$1"
	fi

	printer TAB_PRINT
}
