#!/bin/bash

# $1 - Object
# $2 - Fields
# $3 - Header
printer_init() {
	declare -n LPD=$1
	LPD[rows]=0
	LPD[header]="$3"
	LPD[fields]=$2
}

printer_add() {
	# Local Printer Data
	declare -n LPD=$1

	# We inc before
	let LPD[rows]++

	LPD[${LPD[rows]}]="$2"

}

printer() {
	declare -n PRINT=$1

	local nOC=${PRINT[fields]}
	local table=""
	local delimiter=""
	local line=""

	delimiter="$(${PRG_PRINTF} "%s${MGC_FLD}+" "$(repeatString "${MGC_FLD}+" $nOC)")"
	table="${delimiter}\n${PRINT[header]}\n${delimiter}\n"

	for i in `${PRG_SEQ} 1 ${PRINT[rows]}`; do
		line="${PRINT[$i]}"

		table="${table}${line}\n"
	done

	${PRG_ECHO} -e "${table}\n${delimiter}" | ${PRG_COLUMN} -t -s"${MGC_FLD}" | ${PRG_AWK} '/^\+/{gsub(" ", "-", $0)}1'
	${PRG_ECHO} " (${PRINT[rows]} rows fetched)"
}

# $1 - Title
# $2 - Tablea ID
# $3 - Header
printer_dump_table() {
	local _TITLE=$1
	local _TABLE=$2

	# Lets find the attrs of this relation
	declare -A TAB_ATTR
	TAB_ATTR[id]=$2
	attrs_search TAB_ATTR
	attrs_get_header TAB_ATTR

	declare -A TAB_PRINT
	printer_init TAB_PRINT ${TAB_ATTR[total]} "${TAB_ATTR[header]}"

	declare -A DATA
	DATA[file]=$_TABLE
	init_file DATA

	unset REC
	while next_record DATA REC; do
		local ROW="|"
		local k=0

		for k in `$PRG_SEQ 1 ${#REC[@]}`; do
			# Check if value is null
			if [ ${REC[$k]} == $MGC_NULL ]; then
				ROW="$ROW${GC[NULL_TEXT]}${MGC_FLD}|"
			else
				ROW="$ROW${REC[$k]}${MGC_FLD}|"
			fi
		done

		printer_add TAB_PRINT "$ROW"
	done

	if [ ! "$1" == "" ]; then
		${PRG_ECHO} "$1"
	fi

	printer TAB_PRINT
}
