#!/bin/bash

table_display_init() {
	TMPDISPLAYFILE="temp/data.tmp"
	$PRG_ECHO "$1" > $TMPDISPLAYFILE
}

table_display_add_row() {
	$PRG_ECHO "$1" >> $TMPDISPLAYFILE
}

table_display_print() {
	table_print ',' "$( $PRG_CAT $TMPDISPLAYFILE )"
	echo "(${#rows[@]} rows fetched)"
}

# $1 - Title
# $2 - Table code
# $3 - Fields names
table_display_dump_table() {
	TITLE=$1
	CODTABLE=$2

	table_display_init "$3"

	map_file_rows $CODTABLE
	for row in "${rows[@]}"; do
		map_fields "$row"

		fn=0
		rowa=""
		vir=""

		# Loop all the fields
		for f in "${fields[@]}"; do
			trim inf $f
			if [ "$fn" -eq 0 ]; then
				if tuple_is_alive $inf; then
					break
				fi
				let fn++
				continue
			fi
			local VAL="$inf"
			if [ ${#VAL} == 1 ]; then
				local p=$(echo -en "$VAL" | ${PRG_XXD} -p)
				if [ "$p" == "$MAGIC_CODE_NULL" ]; then
					VAL="$NULL_DISPLAY"
				fi
			fi

			#rowa="$rowa$vir$inf"
			rowa="$rowa$vir${VAL}"

			# Separator
			vir=","
		done
		table_display_add_row "$rowa"
	done
	echo "$TITLE"
	table_display_print
}
