#!/bin/bash

if [ ! $VAR_INCLUDED ]; then
VAR_INCLUDED=1

# DEBUG
#   0 = False
#   1 = True
DEBUG=1

# DBDATA
#   This point to DB Data folder
#	"data" is the default
DBDATA=data

# ERRCODE
#	Could be set for further analysis
ERRCODE=-1

# PROGRAMNAME
#	Name of this program
#	This value is set at bashbd init
PROGRAM="-1"

#####################
# CACHES
#####################
declare -A CACHE_SCHEMA
declare -A CACHE_TABLE

#####################
# GLOBAL CONFIG - GC
#####################
declare -A GC
GC[NULL_TEXT]="(null)"

# To save the original values before the FIRST change
declare -A GC_ORIGINAL

fi
