#!/bin/bash

if [ ! $VAR_INCLUDED ]; then
VAR_INCLUDED=1

# DEBUG
#   0 = False
#   1 = True
DEBUG=1

# BDDATA
#   This point to BD Data folder
#	"data" is the default
BDDATA=data

# ERRCODE
#	Could be set for further analysis
ERRCODE=-1

# PROGRAMNAME
#	Name of this program
#	This value is set at bashbd init
PROGRAM="-1"

#####################
# CACHES
#####################
declare -A CACHE_SCHEMA
declare -A CACHE_TABLE

fi
