#!/bin/bash

drop_schema_execute() {
  local P_SCHEMA=""

	LOGGER_MSG="Drop schema(${TOKENS[SCHEMA_total]}): ${TOKENS[SCHEMA_full]} (cascade: ${TOKENS[CASCADE]})"
	eval $LOGGER DEBUG

	for ((i=1; i<=${TOKENS[SCHEMA_total]}; i++)); do
		local schema="${TOKENS[SCHEMA_${i}]}"

		# Cannot drop schema bashdb
		if [ "$schema" == "bashdb" ]; then
			eval $LOGGER ERROR "Cannot drop schema bashdb"
			return 1
		fi

		declare -A TKNDROPTABLE

		# load SCHEMA_RECORD
		P_SCHEMA="$schema"
		eval $M_GET_SCHEMA

		if [ -z ${SCHEMA_RECORD[REC_POS]} ]; then
		  LOGGER_MSG="Field position not found"
			eval $LOGGER ERROR
			return 1
		fi

		# Check if there are tables within schema
		#  RS = RecordSet
		declare -A RS_DATA_TABLE
		RS_DATA_TABLE[file]=$CTABLE_TABLES
		init_file RS_DATA_TABLE

		LOGGER_MSG="Will search for ${SCHEMA_RECORD[id]}"
		eval $LOGGER DEBUG

		while next_record RS_DATA_TABLE TABLE_RECORD; do
			# Check if is the same schema
			# $1 - ID
			# $2 - Tablename
			# $3 - schemaid
			if [ "$schema_id" == "${TABLE_RECORD[3]}" ]; then
				LOGGER_MSG="Found ${TABLE_RECORD[3]} => ${TABLE_RECORD[2]}"
				eval $LOGGER DEBUG2

				# We found a match, a table that still exists in this schema
				# Must check if CASCADE was supplied
				if [ "${TOKENS[CASCADE]}" == "true" ]; then
					# Call the drop_table
					TKNDROPTABLE[TABLE]="${TABLE_RECORD[2]}"
					drop_table_execute TKNDROPTABLE
				else
					LOGGER_MSG="Still exists objects in this schema. Found table '$schema.${TABLE_RECORD[2]}'"
					eval $LOGGER ERROR
					return 1
				fi
			fi
		done

		# Set the schema as not alive
		LOGGER_MSG="Will mark not alive. file: $CTABLE_SCHEMAS - pos ${SCHEMA_RECORD[REC_POS]}"
		eval $LOGGER DEBUG

		local cvl=0
		let cvl=${SCHEMA_RECORD[REC_POS]}+1
		declare -A CH_DATA
		CH_DATA[table]=$CTABLE_SCHEMAS
		CH_DATA[pos]=$cvl
		CH_DATA[data]="0"
		if ! table_change_data CH_DATA; then
			eval $LOGGER ERROR "Fail to change data on table"
			declare -p CH_DATA
			return 1
		fi

		writeln "Schema ${schema} dropped"
	done
}
