#!/bin/bash

# $1 - Tokens
create_schema_execute() {
	declare -n _SQLTKN=$1
	local i=0
	local IDS=0

	# [ md_table ]
	#  Preparing the Insertion
	declare -A ROW
	ROW[table]=$CTABLE_SCHEMAS

	table_row_init ROW

	# Check if schema exists
	for ((i=1 ; i <= ${_SQLTKN[SCHEMA_total]}; i++)); do
		SCHEMA_NAME=${_SQLTKN[SCHEMA_${i}]}

		# If schema already exists we cant create a new one
		#  - Check IFNOTEXISTS flag
		# [ md_schema ]
		declare -A SS
		declare -A SCHEMA_RECORD
		SS[schema]=$SCHEMA_NAME
		if ! schema_get_struct_by_name SS SCHEMA_RECORD; then
			table_row_add_value ROW ${MGC_NULL} "${SCHEMA_NAME}"
		else
			# Before giving error lets check IFNOTEXISTS
			if [ "${_SQLTKN[IFNOTEXISTS]}" == "true" ]; then
				# LOGGER_MSG="Schema ${SCHEMA_NAME} already exists. IFNOTEXISTS supplied, not giving error."
				# eval $LOGGER WARNING

				writeln "NOTE: skipping schema ${SCHEMA_NAME}, because already exists and IFNOTEXISTS supplied"
				continue
			else
				LOGGER_MSG="Schema ${SCHEMA_NAME} already exists"
				eval $LOGGER ERROR
				return 1
			fi
		fi
	done

	# [ md_table ]
	table_row_insert ROW

	# [ functions ]
	timing_process

	# finishing
	writeln "CREATE SCHEMA OK"
	return 0
}
