#!/bin/bash

table_execute() {
	declare -n _SQLTKN=$1
	local OUT=""
	local value="${_SQLTKN[TABLE]}"
	
	LOGGER_MSG="Table: $value"
	eval $LOGGER DEBUG

	# Find the table struct
	P_TABLE="$value"
	eval $M_GET_TABLE

	SAMPLE=-1
	if [ "${TOKENS[SAMPLE]}" == "true" ]; then
		SAMPLE=${GC[SAMPLE_COUNT]}
	fi

	hex_to_int ID "${TABLE_RECORD[1]}"

  # Just call the printer_dump_table
	# [ printer ]
	printer_dump_table "" ${ID} $SAMPLE
}
