#!/bin/bash

truncate_execute() {
	LOGGER_MSG="Total Tables: ${TOKENS[TABLE_total]}"
	eval $LOGGER DEBUG

	local sz=${TOKENS[TABLE_total]}
	local i=0

  for (( i=1; i<=$sz; i++ )); do
		local table="${TOKENS[TABLE_${i}]}"
		declare -A TS

		LOGGER_MSG="Truncate table: $table"
		eval $LOGGER DEBUG

		# Find the table
		TS[table]="$table"
		if ! table_get_struct_by_name TS RECORD; then
			LOGGER_MSG="Table '${TS[table]}' not found"
			eval $LOGGER ERROR
			return 1
		fi

		local file_id
		hex_to_int file_id ${RECORD[1]}

		LOGGER_MSG="Truncating table ${TS[table]} id: ${file_id}"
		eval $LOGGER DEBUG

		${PRG_ECHO} "${MGC_TABLE}" > ${file_id}

		writeln "Table \"${TS[table]}\" truncated"
	done
}
