#!/bin/bash

show_execute() {
  declare -n _SQLTKN=$1

  local _TYPE=-1
  local _TYPENAME=${_SQLTKN[TYPE]}
  local _OBJECT=${_SQLTKN[OBJECT]}
  local _OBJECTID=-1

  declare -p TOKENS

  if [ -z ${_SQLTKN[TYPE]} ]; then
    LOGGER_MSG="Invalid syntax for SHOW command"
    eval $LOGGER ERROR $LOGGER_MSG
    return 1
  fi

  _TYPE=${COMMENT_TYPE_MAP[${_TYPENAME^^}]}
  if [ "$_TYPE" == "" ]; then
    LOGGER_MSG="SHOW COMMENT on $_TYPENAME not supported"
    eval $LOGGER ERROR $LOGGER_MSG
    return 1
  fi

  # Find the objectId
  case "$_TYPE" in
    $COMMENT_TYPE_SCHEMA)
      P_SCHEMA="$_OBJECT"
      eval $M_GET_SCHEMA
      _OBJECTID=${SS[id]}
      ;;
  esac

    # Check if exists
  # [ md_comment ]
  declare -A CS
  CS[type]=${_TYPE}
  CS[objectId]=${_OBJECTID}
  if ! comment_get_struct_by_type_objectId CS RECORD; then
    LOGGER_MSG="Comment not found"
    eval $LOGGER ERROR
    return 1
  fi

  declare -A TAB_PRINTER
  TAB_PRINTER[header]="COMMENT"
  TAB_PRINTER[fields]=1
  TAB_PRINTER[0]="${RECORD[4]}"

  printer TAB_PRINTER

  return 0

}