#!/bin/bash

# Functions for using in the tests

# $1 - First
# $2 - Value to check
test_eq() {
	if [ "$1" == "$2" ]; then
		echo "OK ($1)"
	else
		echo "NOK $1 <> $2"
	fi
}

test_init() {
	declare -n _TEST=$1
	_TEST[name]="$2"
	_TEST[passed]=0
	_TEST[total]=0
	_TEST[fail]=0
	_TEST[result]=0
	log_stdout "Testing: $2"
}

test_passed() {
	declare -n _TEST=$1
	_TEST[result]=0
	
	((${_TEST[passed]}=${_TEST[passed]}+1))
	((${_TEST[total]}=${_TEST[total]}+1))
}

test_fail() {
	declare -n _TEST=$1
	_TEST[result]=0
	
	((${_TEST[fail]}=${_TEST[fail]}+1))
	((${_TEST[total]}=${_TEST[total]}+1))
}

test_finish() {
	declare -n _TEST=$1
	if [ ${_TEST[fail]} -gt 0 ]; then
	  _TEST[result]=1
	else
	  _TEST[result]=0
	fi
}

log() {
	echo "$1"
}

log_stdout() {
	echo "$1" >&3
	echo "$1"
}