#!/bin/bash
readonly CSCHEMA_BASHBD=1
readonly CSCHEMA_PUBLIC=2

readonly CTABLE_SCHEMAS=1
readonly CTABLE_TABLES=2
readonly CTABLE_ATTRS=3

readonly CSCHEMA_BASHBD_N="bashbd"
readonly CSCHEMA_PUBLIC_N="public"

row_init() {
	ROW[FIELDS]=$1
	ROW[ROWS]=0
}

row_add_value() {
	VALUES=("$@")

	fn=0
	let ROW[ROWS]=${ROW[ROWS]}+1
	rown=${ROW[ROWS]}
	for pos in `seq 0 2 ${#VALUES[@]}`; do
		SIZE="${VALUES[pos]}"
		VALUE="${VALUES[pos+1]}"

		if [ "$SIZE" == "" ]; then
			continue
		fi

		let fn=$fn+1
		ROW[$rown,SIZE_$fn]="$SIZE"
		ROW[$rown,VALUE_$fn]="$VALUE"
	done
}

row_append_simple() {
	local _TABLE=$1

	echo "Total rows: ${ROW[ROWS]}"
	CROW=""

	for i in `seq 1 ${ROW[ROWS]}`; do
		for f in `seq 1 ${ROW[FIELDS]}`; do
			SIZE="${ROW[$i,SIZE_$f]}"
			VALUE="${ROW[$i,VALUE_$f]}"

			CROW=`printf "%s%${SIZE}s" "${CROW}" "${VALUE}"`
		done
	done

	echo "$CROW" >> $_TABLE
}

unset ROW
declare -A ROW

##########
# TABLE: SCHEMAS
row_init 2	# Number of fields
row_add_value   4 "$CSCHEMA_BASHBD" \
		      200 "bashbd"
row_add_value   4 "$CSCHEMA_PUBLIC" \
			  200 "public"

row_append_simple $CTABLE_SCHEMAS

##########
# TABLE: TABLES
row_init 3
row_add_value  4 1 \
			 200 "schemas" \
			   4 1
row_add_value  4 2 \
			 200 "tables" \
			   4 1
row_add_value  4 3 \
			 200 "attrs" \
			   4 1
row_append_simple $CTABLE_TABLES

##############
# TABLE: ATTRS
#row_init 3
#row_add_value
