#!/bin/bash

##############
# Program to dump file contents
##############

FILE=$1
if [ ! -f $FILE ]; then
	echo "File '$FILE' not found. Exiting"
	exit 1
fi

. const
. storage
. temp/table
. functions
. log

# Initialize this variable with a default value to not break
#  LOGGER calls
PRG_PRINTF="printf"

# [ functions ]
find_binaries

declare -A ATABLE

# $1 - Field N
# $2 - Value
check_size() {
	atual=${ATABLE[S_$1]}
	input=${#2}

	if [ -z $atual ]; then
		atual=0
	fi

	if [ "$input" -gt "$atual" ]; then
		ATABLE[S_$1]=$input
	fi
}

echo "Dumping: $FILE"

TMP=$($PRG_DD if=$FILE ibs=1 count=1 conv=notrunc status=none | ${PRG_XXD} -p)
VALUE=${TMP^^}

get_magic_code_name OUT $VALUE

echo "  Type: $VALUE ($OUT)"

# Using the 1E hex code we want to split one row per array
#  1E = Record delimiter

# -t = Remove delimitador no final de cada linha (sem enter)
# -s = Descarta a primeira linha (File Type)
# -O = Inicia atribuição no index x
# -d = Delimitador de record
mapfile -t -s 1 -O 1 -d `echo -en "\x1E"` DATA < $FILE

#echo "Total Rows: ${#DATA[@]}"
ATABLE[ROWS]=${#DATA[@]}

rown=0
TABDATA=""
TABFLD="Row N, Alive"

# Loop in the records
for i_row in "${DATA[@]}"; do
	# 1D is Field Delimiter
	# Break the row
	mapfile -t -O 1 -d `echo -en "\x1D"` FLD <<<$(echo "${i_row[@]}")

	let rown++
	#echo "Row: ${rown}"

	# Loop in the fields on the record
	rowf=0
	TABSEP=""

	TABDATA="${TABDATA}$rown"

	for f in "${FLD[@]}"; do
		# Like a trim
		inf="$(echo $f)"

		# Check size
		check_size $rowf "${inf}"

		# Metadata
		if [ "$rowf" -eq 0 ]; then
			:
			#echo "Metadata"
			#echo "   Alive? ${inf:0:1}"
		else
			echo " $rowf = $inf (`echo -n $inf | hexdump -v -e '/1 "%02X "'`)"
			if [ "${rown}" -eq 1 ]; then
				TABFLD="$TABFLD,Fld${rowf}"
			fi
		fi

		let rowf++

		VAL="${inf}"
		# Check if value is null
		if [ ${#VAL} == 1 ]; then
			RET=$(echo -en "$VAL" | xxd -p)
			echo " == $RET"
			if [ "$RET" == "$MGC_NULL" ]; then
				VAL="(null)"
			fi
		fi

		#TABDATA="${TABDATA},${inf}"
		TABDATA="${TABDATA},${VAL}"
		TABSEP=","

		#ATABLE[${rown}_${rowf}]="$inf"
		ATABLE[${rown}_${rowf}]="$VAL"
	done

	# Do not remove the enter in the next line
	TABDATA="$TABDATA
"

	# Just in the Row #1 (That must be the header of the object)
	if [ "$rown" == 1 ]; then
		ATABLE[TF]=$rowf
	fi
done

echo "Total fields: ${ATABLE[TF]}"
echo "Total Rows: ${ATABLE[ROWS]}"
echo ""

#echo "||${TABFLD},${TABDATA}||"

printTable ',' "${TABFLD}
${TABDATA}"
