#!/bin/bash

b=1

a(){
	local me=$(head -c 500 /dev/urandom | tr -dc 'a-zA-Z0-9~!@#$%^&*_-' | fold -w 5 | head -n 1)
	echo $b
	if [ $b == 4 ] ; then
		return
	fi

	echo "($me) antes: $a"
	#local a="asd$b"
	declare a="asd$b"
	#a="asd$b"
	echo "($me) value: $a"
	let b++
	a
	echo "($me) voltei"
	echo "($me) depois: $a"
}
a
echo $a
