#!/bin/bash

CTABLE_SCHEMA_ID=1
CROW_LANG=(int 200 200)
CROW_DEF_SCHEMA=(int 200)

# $1 - Out Read
# $2 - Name
# $3 - Total
# $4 - Position
read_table() {
	local _RET=$1
	VALUE=`dd if=$2 ibs=1 count=$3 skip=$4 conv=notrunc status=none`
	RES=$?
	eval $RET="$VALUE"
	return $RES
}

get_size_row() {
	local _RET=$1
	VALUES=($@)
	SZ=0
	#echo ${VALUES[@]}

	for pos in `seq 2 ${#VALUES[@]}`; do
		#echo "|${VALUES[pos-1]}|"
		case ${VALUES[pos-1]} in
			-1)
				let SZ=-1
				break
				;;
			int) let SZ=$SZ+8 ;;
			*) let SZ=$SZ+${VALUES[pos-1]} ;;
		esac
	done

	eval $_RET=$SZ
}

get_schema_id_simple() {
	local _RET=$1

	get_size_row ROW_SZ ${CROW_DEF_SCHEMA[@]}
	echo $ROW_SZ

	
}

get_table_id_simple() {
	#  Get the schema ID
	local _RET=$1
	local SCHEMA=$2
	local TABLE=$3

	get_schema_id_simple SCHEMA_ID $SCHEMA $TABLE
}

#get_size_row SIZE ${CROW_DEF[@]}
#get_size_row SIZE ${CROW_LANG[@]}

get_table_id_simple ID bashbd tables
