#!/bin/bash

LOGGER="log \${FUNCNAME[0]} \${LINENO} "

log() {
	if [ -z ${3} ]; then
		MSG="${LOGGER_MSG}"
	else
		MSG="${3}"
	fi

	#echo ${!3}

	echo "$1:$2" "${MSG}"

	unset LOGGER_MSG
}

fnc() {
	#echo ${FUNCNAME[0]}
	#log ${FUNCNAME[0]}
	
	VALUE="teste variable"

	#echo $VALUE
	#eval $LOGGER "variable: \"asd\" '$VALUE' asd asd"

	LOGGER_MSG="Aqui 'asd' vai um valor"
	eval $LOGGER

	eval $LOGGER "ASD"
}

fnc
