#!/bin/bash

TOTAL=200

seq_style() {
	echo "Using sequence"

for i in `seq 1 $TOTAL`; do
	:
done
}

num_style() {
	echo "Using num"
	for i in {1..200}; do
		:
	done
}

c_style() {
	echo "Using c style"
	for ((c =1; c<=$TOTAL; c++ )); do
		:
	done
}

inf_style() {
	echo "Using -- style"

	T=$TOTAL
	while [ true ]; do
		let T--
		if [ $T == 0 ]; then
			break
		fi
	done
}

eval_style() {
	echo "Using eval style"
	for i in $(eval echo {1..$TOTAL}); do
		:
	done
}

time seq_style

time num_style

time c_style

time inf_style

time eval_style
