#!/bin/bash

val=0
max=10000

fnc_1() {
	for pos in `seq 1 10000`; do
		let val=$val+$pos
	done
}

fnc_2() {
	for pos in `seq 1 10000`; do
		val=$(($val+$pos))
	done
}

fnc_3() {
	pos=0
	while [ $((++pos)) -le $max ]; do
		let val=$val+$pos
	done
}

fnc_4() {
	pos=$max
	while [ $((--pos)) -ge 0 ]; do
		let val=$val+$pos
	done
}

fnc_5() {
	for pos in {1..10000}; do
		let val=$val+$pos
	done
}
fnc_6() {
	awk 'BEGIN { while (count++<10000) val=val+count; print val }'
}

case "$1" in
	1) fnc_1 ;;
	2) fnc_2 ;;
	3) fnc_3 ;;
	4) fnc_4 ;;
	5) fnc_5 ;;
	6) fnc_6 ;;
esac

echo $val
