#!/bin/bash

. parserv2

SQL='  SET display="text";'
#SQL='  ST display="text";'
#SQL='SET a=b, c=d'
#SQL="set a=3, dfddf=fvfvfv, asdasdasd=1,121231=11;"
#SQL='truncate table tab1'
#SQL='truncate table tab1,tab2;'
#SQL='truncate table tab1,tab2'
#SQL='truncate table tab1, tab2 ;'
#SQL="truncate tab1"
#SQL=" select 1";
#SQL="select col1 as fld from table1 tab"
#SQL="select 1 as fld"
#SQL="select 1, 2 from tabela"
#SQL="select col1, col2 as fld from table"
#SQL="select 1, 2 from tabela tab, tabela2 ta"
#SQL='select 1 *2, asd, col1=col2';
#SQL="select asd as col, col1, col2=col3 as col4"
#SQL="select sum(col) from tab"
#SQL="select 1=2 as abc"
#SQL="select *, tab.col from tabela"
#SQL="select *, tab.col as col2 from tabela"
#SQL="  CREATE      SCHEMA 'test_schema';"
#SQL='create schema "text";';
#SQL='select f1, f2, "a" as b from tab1'
#SQL="create table tab (id int);"
#SQL="create table tab (id int, col char(100));"
#SQL="delete from tab where val=1"
#SQL="delete from tab a where val=\"asd\"";
#SQL="delete from tab where val=1 and va2=2"
#SQL="select 1 from tab order by 1 desc"
#SQL="insert into tab (col1, col2) values ('ad', asd)"
#SQL="select * from tab"
#SQL="table tab1"
#SQL="SHOW ALL"
#SQL="SHOW display"
#SQL="SHOW ;"
#SQL="select 1 from tab1 a where a.col1 = 1"
#SQL="select 1 + 1"
#SQL="select 1 * 3"
#SQL="create schema sc1, sc2"
#SQL="comment on table asd is 'comment okokos asd';"
#SQL="create schema ifnotexists sc1, sc2"
#SQL="drop schema cascade sc1;"
#SQL="drop schema ifexists sc1;"
#SQL="CREATE TABLE tab( id int notnull , des text default 'val as', def int notnull default 1, col4 text default 1 notnull)"
SQL="CREATE TABLE tab(id int notnull, des text)"
#SQL="DROP TABLE IFEXISTS asd;"
#SQL="REINDEX TABLE asd"
#SQL="select 1 as fld"
#SQL="CREATE INDEX idx01 ON tab (col1)"
#SQL="REINDEX INDEX abc"
#SQL="delete from table1"
#SQL="select 1=2"
#SQL='update table1 set col=col2'
#SQL='select "abc bcd" as fld'
#SQL='select 1 from table1 where true'
#SQL='select a from tab as tabl'
#SQL='select 3-2 as value'

parse_sql "$SQL"
