#!/bin/bash

# $1 - Input
# $2 - Saida Schema
# $3 - Saida Table
parse_table_split() {
	local INPUT="$1"
	local __SCHEMA=$2
	local __TABLE=$3

	dbg_parse "INPUT: ${INPUT}"

	# Appartenly using case is more performatic
	# https://stackoverflow.com/questions/229551/how-to-check-if-a-string-contains-a-substring-in-bash

	case "${INPUT}" in
		*.*)
			echo "Achou"
			eval $__SCHEMA=`echo "${INPUT}" | cut -d. -f1`
			eval $__TABLE=`echo "${INPUT}" | cut -d. -f2`
			return	
			;;
		*) 
			eval $__TABLE="${INPUT}"
			return
			;;
	esac
}
