#!/bin/bash

#. storage

# 8 kbyte
R=8

init_file() {
	declare -n INIT_DATA=$1

	INIT_DATA[pos]=1
	INIT_DATA[data]=$(head -c 8K ${INIT_DATA[file]})
	INIT_DATA[record_num]=0
	INIT_DATA[record]=""
	INIT_DATA[type]="U"	# Unknown

	#echo "${DATA[file]}"

	#tmp=$(dd if=${DATA[file]} ibs=1 count=1 conv=notrunc status=none | xxd -p)
	#value=${tmp^^}

	#value="${DATA[data]:0:1}"
	#echo ${DATA[data]:0:1} | hexdump -C

	#get_magic_code_name OUT $value
	get_magic_code_name OUT ${INIT_DATA[data]:0:1}
	echo " Type: $OUT"

	INIT_DATA[type]="$OUT"
}

next_record() {
	declare -n STG_DATA="$1"
	declare -n TFLD="$2"
	let STG_DATA[record_num]++

	echo "Pos: ${STG_DATA[pos]} - recordnum: ${STG_DATA[record_num]}"

	# Checa se essa row está viva e pega o tamanho
	# O tamanho do header é fixo
	SH_LIVE=1	# Position in header for the "live value"
	SH_SIZE=3	# Position in header for the "record size value"
	SH=8		# Total size of the header
	# 1 -- Record init
	# 2 -- Live or not?
	# 3 -- Field Separator
	# 4..7 -- size
	# 8 -- Data Init

	pos=${STG_DATA[pos]}

	# A nossa posição atual tem que ser um E1
	tmp=${STG_DATA[data]:$pos:1}
	if [ ! "$tmp" == "$MGC_SEP" ]; then
		echo "Magic code não presente. Posição errada"
		return
	fi

	#echo -n $tmp | hexdump -C

	live="${STG_DATA[data]:(($pos+$SH_LIVE)):1}"
	hsz="${STG_DATA[data]:(($pos+$SH_SIZE)):4}"
	sz=$((0x$hsz))

	echo "  | Live? $live"
	echo "  | Size? $hsz ($sz)"

	fields="${STG_DATA[data]:(($pos+$SH)):$sz}"

	echo "|$fields|"
	echo -n "$fields" | hexdump -C

	# Break fields
	mapfile -t -O 1 -d${MGC_FLD} TFLD < <(echo -n "$fields")

	# Andar o pos
	# sz - size of the record
	# SZ_SIZE - size of the header
	echo "Andar: $pos + $sz + $SH"
	let walk=$pos+$sz+$SH
	STG_DATA[pos]=$walk
}
