#!/bin/bash
readonly CODE_MAGIC_TABLE="0A"
readonly CODE_MAGIC_INDEX="0B"
readonly CODE_MAGIC_SEQUENCE="0C"

# $1 - OBJECT
# $2 - RETURN
get_magic_code() {
	local _RET=$2

	case "$1" in
		TABLE)
			eval $_RET="$CODE_MAGIC_TABLE" ;;
		INDEX)
			eval $_RET="$CODE_MAGIC_INDEX" ;;
		SEQUENCE)
			eval $_RET="$CODE_MAGIC_SEQUENCE" ;;
		*)
			echo "Não tratado $1"
			;;
	esac
}

# $1 = OBJECT
# $2 = NAME
storage_create_file() {
	if [ -z $1 ] || [ -z $2 ]; then
		echo "Faltando parametros de entrada"
		return 1
	fi

	local _OBJ=$1
	local _NAME=$2

	get_magic_code $_OBJ MGC

	echo -e -n "\x$MGC" > "$_NAME"
	return 0
}

# $1 - OBJECT
# $2 - NAME
storage_check_mgc() {
	TMP=`dd if=$2 ibs=1 count=1 conv=notrunc status=none | xxd -p`
	VALUE=${TMP^^}

	get_magic_code $1 MGC

	if [ ! "$VALUE" == "$MGC" ]; then
		echo "Tipo de objeto não é valido"
	fi
}

