#!/bin/bash

: <<'FUNCTION'
Description: Search for the table ID
Parameters:
 $1 - OUT ID
 $2 - SCHEMA
 $3 - TABLE
FUNCTION
get_table_id_simple() {
	:
}

: <<'FUNCTION'
Description: Search for the schema ID
Parameters:
 $1 - OUT ID
 $2 - SCHEMA
FUNCTION
get_schema_id_simple() {
	:
}

