#!/bin/bash

: <<'FUNCTION'
Description: Entry function to scan a recordset
Parameters:
  $1 - Recordset
  $2 - Output variable
  $3 - FILTER variable
      $3[STOP] = Stop if found
      $3[total] = Total of filter entries to check
      $3[0,0] = filter 0 fieldNumber
      $3[0,1] = filter 0 value
      $3[0,2] = filter operator (default: equal)
Return Code:
  0 - Found Record
  1 - No record found
FUNCTION
simple_scan() {
  declare -n _OUTPUT="$2"
  declare -n _FILTER=$3
  local _STOP=${_FILTER[stop]}

  unset _OUTPUT

  while next_record $1 REC; do
    local i=0
    local found=0
    # Evaluate filter checks
    for ((i=0; i<${_FILTER[total]};i++)); do
      field="${_FILTER[$i,0]}"
      value="${_FILTER[$i,1]}"
      if [ "${REC[$field]}" == "$value" ]; then
        found=1
        continue
      else
        found=0
        break
      fi
    done

    if [ $found == 1 ]; then
      # [ functions ]
      copy_array REC _OUTPUT

      if [ "$_STOP" == "true" ]; then
        return 0
      fi
    fi
  done

  return 1
}