#!/bin/bash

cmd_menu() {
	if [ "${1^^}" == "HELP" ]; then
		menu_show_help
		return 0
	fi

	# Break in tokens
	# TKN 0 = The command
	# TKN 1 = Option, if the command permits
	local TKN=(${@})

	# Vim shows that using "$array_var[x]:init:end" is wrong, but is correct
	case "${TKN[0]:1:1}" in
		q)  finish 0;;
		## TODO
		## Find a better place to put the menu_list functions
		# menu.menu_list
		c)  menu_list "comments"   $CTABLE_COMMENTS;;
		t)  menu_list "tables"     $CTABLE_TABLES;;
		s)  menu_list "schemas"    $CTABLE_SCHEMAS;;
		f)  menu_list "functions"  $CTABLE_FUNCTIONS;;
		S)  menu_list "sequences"  $CTABLE_SEQUENCE;;
		y)  menu_list "types"      $CTABLE_TYPES;;
		l)  menu_list "languages"  $CTABLE_LANG;;
		i)  menu_list "indexes"    $CTABLE_INDEX;;
		a)  menu_list "attributes" $CTABLE_ATTRS;;
		
		c)  menu_warm_cache "${TKN[1]}";;
		b)  menu_call_function "${TKN[1]}" "${TKN[2]}" "${TKN[3]}";;
		\?)	menu_show_help;;
		*)  echo "Menu Comando $PAR não reconhecido"
	esac

	return 0
}

menu_show_help() {
	writeln "Command menu"
	writeln ""
	writeln "\\?       Show this help"
	writeln ""
	writeln "\\a       List attributes"
	writeln "\\c       List comments"
	writeln "\\f       List functions"
	writeln "\\i       List indexes"
	writeln "\\l       List languages"
	writeln "\\s       List schemas"
	writeln "\\S       List sequences"
	writeln "\\t       List tables"
	writeln "\\y       List types"
	writeln ""
	writeln "\\q     Quit program"
}

###################################################
###################################################
map_file_rows() {
	unset rows
	mapfile -t -s 1 -O 1 -d `$PRG_ECHO -e -n "\x1E"` rows < $1
}

map_fields() {
	unset fields
	mapfile -t -O 1 -d `$PRG_ECHO -en "\x1D"` fields <<<$( $PRG_ECHO "$1")
}

###################################################
###################################################
# $1 - Id of the table to list
menu_list() {
	printer_dump_table "Listing $1" $2
}

menu_warm_cache() {
	# Do the cache if necessary
	cache_do_cache $CTABLE_SCHEMAS
}

menu_call_function() {
	LOGGER_MSG="Call fn: $1"
	eval $1 $2 $3
}
