#!/bin/bash

: <<'COMMENT'
Description of ROW Vector:
	ROWS      => Total row number in the vector
	FIELDS    => Total fields number in the row
	FIELDS_n  => The type of the attributes
    n,VALUE_y => The number of the row, and the values of its attibutes
COMMENT

: <<'FUNCTION'
Description: Return Magic Code by name
Parameters:
  $1 - Return variable
	$2 - Input
FUNCTION
get_magic_code() {
	local _RET=$1

	case "$2" in
		TABLE)
			eval $_RET="$MGC_TABLE" ;;
		INDEX)
			eval $_RET="$MGC_INDEX" ;;
		SEQUENCE)
			eval $_RET="$MGC_SEQUENCE" ;;
		*)
			$PRG_ECHO "Unknown Magic Code $2"
			;;
	esac
}

: <<'FUNCTION'
Description: Return Name based on Magic Code value
Parameters:
  $1 - Return variable
	$2 - Magic Code
FUNCTION
get_magic_code_name() {
	local _RET=$1
	case $2 in
		$MGC_TABLE)	   eval $_RET="TABLE" ;;
		$MGC_INDEX)    eval $_RET="INDEX" ;;
		$MGC_SEQUENCE) eval $_RET="SEQUENCE" ;;
	esac
}

: <<'FUNCTION'
Description: Check if file exists
Parameters:
  $1 - File Name
Returns:
  0 - File exists
	1 - File not exists
FUNCTION
storage_file_exists() {
	if [ -f $1 ]; then
		return 0
	else
		return 1
	fi
}

: <<'FUNCTION'
Description: Function to create file
Parameters:
 $1 = OBJECT
 $2 = NAME
FUNCTION
storage_create_file() {
	local _OBJ=$1
	local _FILE=$2

	if [ -z $2 ]; then
		LOGGER_MSG="Parameter #2 not passed"
		eval $LOGGER ERROR
		return -1
	fi

	storage_file_exists $_FILE
	RES=$?
	if [ "$RES" -eq "0" ]; then
		LOGGER_MSG="Cannot create file. File ($_FILE) already exists"
		eval $LOGGER ERROR
		return -1
	fi

	# [ storage ]
	get_magic_code MGC $_OBJ

	${PRG_ECHO} -en "$MGC" > $_FILE
	${PRG_ECHO} -en "$MGC_SEP" >> $_FILE

	LOGGER_MSG="File ($_FILE) successfully created"
	eval $LOGGER DEBUG2

	return 0
}

: <<'FUNCTION'
Description: Append Magic Code value into file
Parameters:
  $1 - Hex Magic Code
  $2 - File
FUNCTION
storage_append_magic() {
	$PRG_ECHO -en "\x$1" >> $2
}

: <<'FUNCTION'
Description: Convert a ASCII value to its hex representation
Parameters:
 $1 - ASCII value with 2 bytes
FUNCTION
storage_print_magic() {
	# Check length 2 bytes
	if [ ! ${#1} == 2 ]; then
		eval $LOGGER ERROR "Value must have 2 bytes"
		return 1
	fi

	$PRG_ECHO -en "\x$1"
}

: <<'FUNCTION'
Description: Check if object is of the desired type
Parameters:
 $1 - Kind of object (TABLE, INDEX...)
 $2 - File
FUNCTION
storage_check_mgc() {
	TMP=`$PRG_DD if=$2 ibs=1 count=1 conv=notrunc status=none | ${PRG_XXD} -p`
	VALUE=${TMP^^}

  # [ storage ]
	get_magic_code MGC $1

	if [ ! "$VALUE" == "$MGC" ]; then
		$PRG_ECHO "Invalid kind of object"
	fi
}

: <<'FUNCTION'
Description: Simple function to insert into table
# The values must be present in the $ROW variable
# $1 - Table to append data
FUNCTION
row_append_simple() {
	local _TABLE=$1
	local CROW=""	# Used to hold all the records
	local IROW=""	# Used in the inner record
	local METADATA=""
	local rec_size=0

	# Loop in the ROW variable, that can contain one or more rows
	for i in `$PRG_SEQ 1 ${ROW[ROWS]}`; do
		# In this first level of the loop we are in the Record level
		IROW=""

		# Now, loop the fields in this row
		for f in `$PRG_SEQ 1 ${ROW[FIELDS]}`; do

			# Get the value of the field
			I_VALUE="${ROW[$i,VALUE_$f]}"

			# The size of the field
			SIZE="${ROW[FIELDS_$f]}"

			if [ "${I_VALUE}" == "${MGC_NULL}" ]; then
				IROW="${IROW}${I_VALUE}"
			else
				# Check if the data need some special treatment
				case ${SIZE} in
					int)
						# Just check the size -1 and convert to null
						if [ "${I_VALUE}" -eq -1 ]; then
							IROW="${IROW}${MGC_NULL}"
						else
							int_to_hex rec_size 8 ${I_VALUE}
							IROW="${IROW}${rec_size}"
						fi
						;;
					*)
						IROW="${IROW}${I_VALUE}"
						;;
				esac
			fi

			# Put a Field Separator
			if [ ! "$f" == "${ROW[FIELDS]}" ]; then
				IROW="${IROW}${MGC_FLD}"
			fi
		done

		int_to_hex rec_size 4 ${#IROW}

		# This is the end of the ROW, lets put our metadata
		METADATA="1${MGC_FLD}${rec_size}${MGC_HEADER}"

		# The row data finished, put a Record Separator
		CROW="${CROW}${METADATA}${IROW}${MGC_SEP}"
	done

	# Just echo the value to the table
	$PRG_ECHO -n "${CROW}" >> $_TABLE

	# Change to use here-doc that is not affected by the ARG_MAX "limitation"
	# The below code does not work correctly, just left here to remember the attempt and not
	#	  waste time trying again
	#$PRG_CAT -n <<<"${CROW}" >> $_TABLE

	# Data is inserted
}

: <<'FUNCTION'
Description: Initialize the ROW variable
 $n - Type or size of the attribute
 Example:
  row_init int 200
    $1 - type int
    $2 - size 200
FUNCTION
row_init() {
	VALUES=($@)

	# METADATA
	# #1 - Row is alive? 0 No 1 Yes
	ROW[META]="0"
	ROW[FIELDS]="${#}"
	ROW[ROWS]=0

	for i in `$PRG_SEQ 1 ${#}`; do
		ROW[FIELDS_$i]="${VALUES[i-1]}"
	done
}

row_add_value() {
	VALUES=("$@")
	fn=0
	let ROW[ROWS]=${ROW[ROWS]}+1
	rown=${ROW[ROWS]}
	for pos in `$PRG_SEQ 1 ${#VALUES[@]}`; do
		# one more field/attribute
		let fn=$fn+1

		ROW[$rown,VALUE_$fn]="${VALUES[pos-1]}"
	done
}

init_file() {
	# Check if the variable name does not conflict with the name of our
	#  inner variable. If the name is the same we will get circular reference error
	# IFD = Inner File Data
	if [ "$1" == "IFD" ]; then
		eval $LOGGER ERROR "Variable name cannot be IFD"
		return 1
	fi
	declare -n IFD=$1

	if [ "${IFD[file]}" == "" ]; then
		eval $LOGGER ERROR "Table file is missing"
		return 1
	fi

	# Position the cursor at the beginning
	IFD[pos]=1
	# Read 32Kb for now
	IFD[data]=$(${PRG_HEAD} -c 32K ${IFD[file]})
	IFD[record_num]=0
	IFD[record]=""
	IFD[type]="U"	# Unknown

	local ts=$(${PRG_STAT} -c %s ${IFD[file]})

	# Save the type of this relation
	get_magic_code_name OUT ${IFD[data]:0:1}
	IFD[type]="$OUT"
}

: <<'FUNCTION'
Description: Get the next record in the recordset
Parameters:
  $1 - The recordset initialized by init_file function
	$2 - The output variable to hold the record data
Returns:
  0 - OK Record Found
	1 - No more data
	2 - Internal error
FUNCTION
next_record() {
	declare -n STG_DATA="$1"
	declare -n TFLD="$2"

	# Clear the variable
	unset TFLD

	# Check if the record is alive and get the values
	# 1 -- Record init
	# 2 -- Live or not?
	# 3 -- Field Separator
	# 4..7 -- size
	# 8 -- Data Init

	# We do a loop here because we may find not alive records
	while true; do
		# Actual pos
		local pos=${STG_DATA[pos]}

		# Out actual position must be an 1E hex
		local tmp=${STG_DATA[data]:$pos:1}

		if [ "$tmp" == "" ]; then
			eval $LOGGER DEBUG "Next variable is empty. There is no more data"
			return 1
		fi

		if [ ! "$tmp" == "$MGC_SEP" ]; then
			eval $LOGGER ERROR "Magic code not present. Maybe corrupt data or wrong position"
			unset TFLD
			return 2
		fi

		# Size of the record pos + SH_SIZE (Size header)
		local hsz="${STG_DATA[data]:(($pos+$SH_SIZE)):4}"

		# Convert to integer
		local sz=$((0x$hsz))

		# Get the fields value pos + SH (Total Size Header)
		local fields="${STG_DATA[data]:(($pos+$SH)):$sz}"

		if [ "$fields" == "" ]; then
			eval $LOGGER DEBUG2 "Next variable is empty. There is no more data"
			return 1
		fi

		# These lets must be before the alive check
		# Walk the position
		# sz - size of the record
		# SZ_SIZE - size of the header
		let walk=$pos+$sz+$SH
		STG_DATA[pos]=$walk
		let STG_DATA[record_num]++

		# Check if is alive
		local live="${STG_DATA[data]:(($pos+$SH_LIVE)):1}"
		if [ ! "$live" == "1" ]; then
			# This row is not alive, continue to the next
			continue
		fi

		# FOUND A LIVING RECORD

		# Break fields
		mapfile -t -O 1 -d${MGC_FLD} TFLD < <(${PRG_ECHO} -n "$fields")
		RES=$?
		if [ ! "$RES" == 0 ]; then
			eval $LOGGER ERROR "Error in mapfile to get fields"
			return 2
		fi

		# When the last field is empty, like a char = "" does not "open" correctly
		# So, if the last value of the fields variable is 1D=MGC_FLD
		#	we must create a new field in the end of the TFLD
		# The extra space is needed, another way to do is ${VAR:0-1}
		if [ "${fields: -1}" == "$MGC_FLD" ]; then
			local newfld=${#TFLD}
			TFLD[$newfld]=""
		fi

		# Negative field
		# see [ const ] for more info
		TFLD[$REC_TOT]="${#TFLD[@]}"
		TFLD[$REC_POS]="$pos"
		TFLD[$REC_TAB]="${STG_DATA[file]}"
		TFLD[$REC_SZ]=${#fields} 
		TFLD[$REC_IP]=1

		break
	done

	return 0
}
