#!/bin/bash

if [ ! $VAR_INCLUDED ]; then
VAR_INCLUDED=1

# DEBUG
#   0 = False
#   1 = True
DEBUG=1

# DBDATA
#   This point to DB Data folder
#	"data" is the default
DBDATA=data

# ERRCODE
#	Could be set for further analysis
ERRCODE=-1

# PROGRAMNAME
#	Name of this program
#	This value is set at bashbd init
PROGRAM="-1"

#####################
# CACHES
#####################
declare -A CACHE_SCHEMA
declare -A CACHE_TABLE

#####################
# GLOBAL CONFIG - GC
#####################
declare -A GC
GC[NULL_TEXT]="(null)"
GC[TIMING]=true	            # command \t
GC[MIN_LOG]=8		            # 5 = log
GC[INPLACE]=true            # Use inplace updates if possible (Similar to Postgres HotUpdate)
GC[SHOW_PARSER]=false       # if show parser structure
GC[SHOW_ROWS_FETCHED]=true  # if show how many rows fetched in the command
GC[SAMPLE_COUNT]=5          # Number of rows to sample (TABLE SQL command) if not provided
GC[DEFAULT_SCHEMA]="public" # Default schema to use if not provided

# To save the original values before the FIRST change
declare -A GC_ORIGINAL

fi
